# Generated by Django 2.1.4 on 2020-10-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
