# Generated by Django 2.1.4 on 2020-10-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_callback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='message',
        ),
    ]
