# Generated by Django 2.1.4 on 2020-10-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_transaction_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='made_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
