# Generated by Django 2.1.4 on 2020-10-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_final'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Final',
        ),
    ]
