# Generated by Django 2.1.4 on 2020-10-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20201023_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
    ]
