# Generated by Django 2.1.4 on 2020-10-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20201023_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='made_by',
            new_name='order_id',
        ),
    ]
