# Generated by Django 2.1.4 on 2020-10-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20201023_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
