# Generated by Django 2.1.4 on 2020-10-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20201023_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
