# Generated by Django 2.1.4 on 2020-10-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20201024_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
